### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by jeffgdotorg** [k1nky/netbox-otp-plugin#11]
Hi there, I'm a product manager at NetBox Labs currently cruising for plugins that ought to appear in [our plugin catalog](https://netboxlabs.com/netbox-plugins/). I would love to add `netbox-otp-plugin` as I see it's recently been updated for compatibility with NetBox 4.0.x, but listed plugins must have a license on record. Please consider choosing a license and adding it to the GitHub repo as well as the plugin's PyPI package record.

Thanks for making the NetBox ecosystem amazing!

**Comment by k1nky** [comment]
Hi,

Now the repository and PyPI package has the same Apache 2.0 license.

**Comment by jeffgdotorg** [comment]
Thanks! Your plugin is now listed in the catalog.

If you're interested in taking it a step further and pursuing certification, check out the [program details](https://github.com/netbox-community/netbox/wiki/Plugin-Certification-Program).
