### ISSUE TITLE
Netbox 4.1.0 compatibility

### ISSUE THREAD

**Issue by bangingheads** [k1nky/netbox-otp-plugin#14]
Netbox 4.1.0 removed ``AUTH_EXEMPT_PATHS`` which causes the plugin unable to migrate.

```
File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/netbox_otp_plugin/__init__.py", line 15, in <module>
    netbox_settings.AUTH_EXEMPT_PATHS = netbox_settings.AUTH_EXEMPT_PATHS + (f'/{netbox_settings.BASE_PATH}plugins/otp',)
AttributeError: partially initialized module 'netbox.settings' has no attribute 'AUTH_EXEMPT_PATHS' (most likely due to a circular import)
```

https://github.com/netbox-community/netbox/pull/16662

**Comment by Omgzilla** [comment]
First of all, thank you so much for this plugin! 

Getting the same issue. Is it safe to just remove the lines ourselves or should we wait for an update?

**Comment by k1nky** [comment]
Thank you for your feedback.

@Omgzilla Since version 4.1.0 `AUTH_EXEMPT_PATHS` is no longer used and it is safe to remove these lines.

Please try [v1.3.0](https://github.com/k1nky/netbox-otp-plugin/releases/tag/v1.3.0). It is compatible with NetBox 4.1.

**Comment by Omgzilla** [comment]
Yes! Will try it today. Thanks a lot!

**UPDATE**
It worked flawlessly! Migrated from v3.7.7 -> v4.1.2.
Thanks again!
