### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by kinokocorp** [k1nky/netbox-otp-plugin#2]
Hello,

Thank you for your plugin.
There is a typo in your readme : 
```
# BAD
echo nextbox_otp_plugin >> local_requirements.txt
# GOOD
echo netbox-otp-plugin >> local_requirements.txt
```

**Comment by kinokocorp** [comment]
Still a typo ^^
There is an extra x in "echo ne**X**tbox-otp-plugin >> local_requirements.txt"

**Comment by k1nky** [comment]
I did it. Thanks a lot.
