### ISSUE TITLE
Bug: OTP input field removes remote authentication backends

### ISSUE THREAD

**Issue by Faabvk** [k1nky/netbox-otp-plugin#5]
**Bug description**
When having the plugin enabled, and using a remote authentication backend (SAML in my case), the buttons to log in with a remote backend disappear, in favor of the OTP code input field.

**To Reproduce**
1. Set up a remote authentication backend (OpenID, SAML, Social SSO)
2. Enable the plugin
3. Go to the login page

**Expected behavior**
I should see the login form, with OTP input field, and the remote backends I have enabled

**Screenshots**
Login page without OTP plugin, but with remote backend:
![image](https://user-images.githubusercontent.com/36154889/230375769-8374580b-182e-4017-bf79-3df3b35e42a4.png)
Login page with OTP plugin and remote backend:
![image](https://user-images.githubusercontent.com/36154889/230374439-d545affb-a3d2-468e-ac73-d1bd329fd7b2.png)
Expected result (mockup):
![mockup](https://user-images.githubusercontent.com/36154889/230375063-6f405739-c26e-4587-ba1d-d57d4b55c712.png)

**Version info**
Netbox v3.4.2
netbox-otp-plugin latest

**Comment by k1nky** [comment]
Thanks for your report. I have fixed it in the and after the final check I will add it to the new version.
