### ISSUE TITLE
The page isn’t redirecting properly

### ISSUE THREAD

**Issue by BH-NetAdmin** [k1nky/netbox-otp-plugin#7]
If "Login Required" is set to true in the configuration file, I receive the error "The page isn’t redirecting properly" from the browser, when trying to access netbox.

Netbox Ver. 3.5.3
Plugin Ver. 1.0.5

**Comment by andersonit** [comment]
I'm having the same issue.  I have LOGIN_REQUIRE = True in configuration.py and using Netbox 3.5.3 with the latest Plugin version.  The browser gives error: ERR_TOO_MANY_REDIRECTS.

**Comment by andersonit** [comment]
I'm having the same issue. I have LOGIN_REQUIRE = True in configuration.py and using Netbox 3.5.3 with the latest Plugin version. The browser gives error: ERR_TOO_MANY_REDIRECTS when bringing up the login page.

**Comment by k1nky** [comment]
It duplicates #6. 

Please, update the plugin.
