### ISSUE TITLE
Prepare for NetBox v4.0

### ISSUE THREAD

**Issue by Creepios** [k1nky/netbox-otp-plugin#8]
NetBox 4.0 has been released and as I think that this is a great plugin, I hope it will be updated.

See migration notes at https://docs.netbox.dev/en/feature/plugins/development/migration-v4/
Edit: Fixed by #9

**Comment by deanfourie1** [comment]
I second this, would love to see an update to this awesome plugin!

**Comment by marco012024** [comment]
First of all, thanks a lot for the plugin @k1nky !

I have created a fork with a working version for Netbox 4.x.

Cheers

**Comment by deanfourie1** [comment]
How do I install a fork? Thanks

**Comment by marco012024** [comment]
First, I'm absoluty no expert in creating python package or Github! 

I made the changes to the plugin out of necessity to get the plugin working again after upgrading to the latest Netbox version and thought i should share it with the community. 

Guessing, unless k1nky isn't committing the changes and uploading a new version to PyPi, you can only download the source code from my fork and install it manually. 


In the source directory run:
`python3 setup.py sdist`

This will create the PyPi archive in the `dist` folder. 
You can add the path to the archive into your `/opt/netbox/local_requirements.txt` and run the `sudo ./upgrade.sh`   command in your `/opt/netbox/` folder.

Example: `/opt/netbox/local_requirements.txt`
`/path/to/archive/netbox_otp_plugin-1.0.8.tar.gz`

**Comment by marco012024** [comment]
> How do I install a fork? Thanks

First, I'm absoluty no expert in creating python packages or how to properly use Github! 

I made the changes to the plugin out of necessity to get the plugin working again after upgrading to the latest Netbox version and thought i should share it with the community. 

Guessing, unless k1nky isn't committing the changes and uploading a new version to PyPi, you can only download the source code from my fork and install it manually. 

How I'am currently running it.

In the source directory of my forked [sourcecode ](https://github.com/marco012024/netbox-otp-plugin/releases/tag/v.1.0.8) run:
`python3 setup.py sdist`

This will create the PyPi archive in the `dist` folder. 
You can add the path to the archive into your `/opt/netbox/local_requirements.txt` and run the `sudo ./upgrade.sh`   command in your `/opt/netbox/` folder.

Example: "/opt/netbox/local_requirements.txt"
`/path/to/archive/netbox_otp_plugin-1.0.8.tar.gz`

I hope this helps! Cheers! ;)

**Comment by deanfourie1** [comment]
Thanks, so i'll use wget to download your source zip,
extract it.

Does it matter where its extracted? Do I even extract it?

Just that you mention running the python3 setup.py sdist, 

But then the path in local_requirements points to the .tar.gz archive, making me think its not extracted, literally just pointing to downloaded file

Thanks for your patience.

**Comment by Creepios** [comment]
> > How do I install a fork? Thanks
> 
> First, I'm absoluty no expert in creating python packages or how to properly use Github! 
> 
> I made the changes to the plugin out of necessity to get the plugin working again after upgrading to the latest Netbox version and thought i should share it with the community. 
> 
> Guessing, unless k1nky isn't committing the changes and uploading a new version to PyPi, you can only download the source code from my fork and install it manually. 
> 

@k1nky Can you please do us a favor and accept the pull request and publish a python package?
That would be very nice, thanks!

**Comment by marco012024** [comment]
@deanfourie1 
Hi! 
Here's the prepared package. This doesn't need to be extracted, just link it in local_requirements according to your path on the server. 
[netbox_otp_plugin-1.0.8.tar.gz](https://github.com/k1nky/netbox-otp-plugin/files/15376300/netbox_otp_plugin-1.0.8.tar.gz)

Cheers!

**Comment by deanfourie1** [comment]
Thank you both thats working for me.

**Comment by deanfourie1** [comment]
Is this still working for you guys, after 4.0.3 update?

**Comment by Creepios** [comment]
@marco012024 Can you take a look over #10 ? This would be awesome!

**Comment by k1nky** [comment]
Thank you for your feedback, especially @Creepios and @marco012024.
I have released a new version 1.1.0 with NetBox v4 support. The new version is also available in the PyPI repository.

**Comment by marco012024** [comment]
Awesome! Thanks!

**Comment by dasJ** [comment]
@k1nky Could you also add a GitHub release so it shows up in GH RSS feeds?

**Comment by k1nky** [comment]
> @k1nky Could you also add a GitHub release so it shows up in GH RSS feeds?

@dasJ Sorry for the long answer, yes of course.
